# Copyright (c) 2024-2026 T1 Agentics LLC
# SPDX-License-Identifier: Apache-2.0

"""
Riggs Playbook Agent

Provides Riggs with full control over playbook creation, modification, and execution.
Key capabilities:
- Automatic playbook selection for alerts (by tags, alert_types, severity)
- Autonomous execution when allowed
- Building playbooks from alerts
- Adding/updating/deleting nodes
- Creating custom functions and lists
- Recommending improvements and integrations
"""

import json
import logging
import uuid
from datetime import datetime
from typing import Dict, Any, List, Optional, Tuple
from pydantic import BaseModel, Field
from enum import Enum

logger = logging.getLogger(__name__)


# ============================================================================
# Models
# ============================================================================

class PlaybookSelection(BaseModel):
    """Result of playbook selection for an alert."""
    selected_playbook: Optional[Dict[str, Any]] = None
    match_score: float = 0.0
    match_reasons: List[str] = Field(default_factory=list)
    alternatives: List[Dict[str, Any]] = Field(default_factory=list)
    requires_approval: bool = True
    can_auto_execute: bool = False


class AutonomyCheck(BaseModel):
    """Result of checking if Riggs can run autonomously."""
    can_run: bool = False
    requires_approval: bool = True
    blocking_reasons: List[str] = Field(default_factory=list)


class PlaybookAnalysis(BaseModel):
    """Analysis of an alert for playbook purposes."""
    matching_playbooks: List[Dict[str, Any]] = Field(default_factory=list)
    missing_integrations: List[str] = Field(default_factory=list)
    recommended_actions: List[Dict[str, Any]] = Field(default_factory=list)
    should_build_new: bool = False
    analysis_summary: str = ""


class PlaybookRecommendation(BaseModel):
    """A recommendation for improving a playbook."""
    type: str  # add_node, update_node, add_edge, add_error_handling, etc.
    description: str
    reasoning: str
    priority: str = "medium"  # high, medium, low
    auto_apply: bool = False
    changes: Dict[str, Any] = Field(default_factory=dict)


class IntegrationRecommendation(BaseModel):
    """A recommendation for adding an integration."""
    integration_name: str
    integration_type: str
    reason: str
    use_case: str
    node_suggestions: List[Dict[str, Any]] = Field(default_factory=list)


class PlaybookDraft(BaseModel):
    """Draft playbook generated by Riggs."""
    name: str
    description: str
    trigger_conditions: Dict[str, Any]
    canvas_data: Dict[str, Any]
    tags: List[str] = Field(default_factory=list)
    alert_types: List[str] = Field(default_factory=list)


# ============================================================================
# Riggs Playbook Agent
# ============================================================================

class RiggsPlaybookAgent:
    """
    Riggs has full control over playbook creation and modification.
    """

    def __init__(self):
        pass

    # ========================================================================
    # Automatic Playbook Selection
    # ========================================================================

    async def select_playbook_for_alert(
        self,
        alert: Dict[str, Any]
    ) -> PlaybookSelection:
        """
        Automatically select the best playbook for an alert.

        Selection algorithm:
        1. Filter by is_enabled=True AND riggs_allowed=True
        2. Match by alert_types (exact match)
        3. Match by tags (fuzzy match on alert content)
        4. Match by severity_filter
        5. Match by data_sources
        6. Sort by priority (higher wins)
        7. If multiple matches, use riggs_confidence
        """
        try:
            from services.postgres_db import postgres_db

            if not postgres_db.connected:
                return PlaybookSelection()

            async with postgres_db.tenant_acquire() as conn:
                # Get all enabled playbooks that Riggs can use
                rows = await conn.fetch('''
                    SELECT * FROM playbooks
                    WHERE is_enabled = TRUE
                    ORDER BY priority DESC, riggs_confidence DESC NULLS LAST
                ''')

                if not rows:
                    return PlaybookSelection(match_reasons=["No enabled playbooks found"])

                # Extract alert metadata
                alert_type = alert.get('type', alert.get('alert_type', 'unknown'))
                alert_severity = alert.get('severity', 'medium')
                alert_source = alert.get('source', alert.get('data_source', ''))
                alert_tags = self._extract_alert_tags(alert)

                candidates = []

                for row in rows:
                    playbook = self._row_to_dict(row)
                    score = 0
                    reasons = []

                    # Check alert_types match
                    pb_alert_types = playbook.get('alert_types', [])
                    if pb_alert_types:
                        if alert_type.lower() in [t.lower() for t in pb_alert_types]:
                            score += 40
                            reasons.append(f"Alert type '{alert_type}' matches")
                        elif any(t.lower() in alert_type.lower() for t in pb_alert_types):
                            score += 20
                            reasons.append(f"Alert type partially matches")

                    # Check tags match
                    pb_tags = playbook.get('tags', [])
                    if pb_tags and alert_tags:
                        matching_tags = set(pb_tags) & set(alert_tags)
                        if matching_tags:
                            score += len(matching_tags) * 10
                            reasons.append(f"Tags match: {', '.join(matching_tags)}")

                    # Check severity filter
                    pb_severities = playbook.get('severity_filter', [])
                    if pb_severities:
                        if alert_severity.lower() in [s.lower() for s in pb_severities]:
                            score += 15
                            reasons.append(f"Severity '{alert_severity}' matches filter")

                    # Check data source
                    pb_sources = playbook.get('data_sources', [])
                    if pb_sources and alert_source:
                        if any(s.lower() in alert_source.lower() for s in pb_sources):
                            score += 10
                            reasons.append(f"Data source matches")

                    # Boost by priority
                    score += (playbook.get('priority', 50) / 10)

                    # Boost by Riggs confidence
                    if playbook.get('riggs_confidence'):
                        score += playbook['riggs_confidence'] * 5

                    if score > 0:
                        candidates.append({
                            "playbook": playbook,
                            "score": score,
                            "reasons": reasons
                        })

                # Sort by score
                candidates.sort(key=lambda x: x['score'], reverse=True)

                if not candidates:
                    return PlaybookSelection(
                        match_reasons=["No matching playbooks found"],
                        should_build_new=True
                    )

                # Best match
                best = candidates[0]
                selected = best['playbook']

                # Check if can auto-execute
                can_auto = (
                    selected.get('riggs_allowed', False) and
                    not selected.get('requires_approval', True)
                )

                return PlaybookSelection(
                    selected_playbook=selected,
                    match_score=best['score'],
                    match_reasons=best['reasons'],
                    alternatives=[c['playbook'] for c in candidates[1:5]],
                    requires_approval=selected.get('requires_approval', True),
                    can_auto_execute=can_auto
                )

        except Exception as e:
            logger.error(f"Failed to select playbook: {e}")
            return PlaybookSelection(match_reasons=[f"Error: {str(e)}"])

    async def can_run_autonomously(
        self,
        playbook_id: str,
        alert: Dict[str, Any]
    ) -> AutonomyCheck:
        """
        Check if Riggs can run this playbook without human intervention.
        """
        try:
            from services.postgres_db import postgres_db

            blocking_reasons = []

            async with postgres_db.tenant_acquire() as conn:
                playbook = await conn.fetchrow(
                    "SELECT * FROM playbooks WHERE id = $1",
                    uuid.UUID(playbook_id)
                )

                if not playbook:
                    return AutonomyCheck(
                        can_run=False,
                        blocking_reasons=["Playbook not found"]
                    )

                # Check enabled
                if not playbook['is_enabled']:
                    blocking_reasons.append("Playbook is not enabled")

                # Check riggs_allowed
                if not playbook['riggs_allowed']:
                    blocking_reasons.append("Playbook does not allow Riggs execution")

                # Check requires_approval
                requires_approval = playbook['requires_approval']

                # Check severity threshold (critical/high can bypass approval)
                alert_severity = alert.get('severity', 'medium').lower()
                auto_approve_severities = ['critical', 'high']

                # Check integrations are configured
                canvas_data = playbook.get('canvas_data')
                if canvas_data:
                    if isinstance(canvas_data, str):
                        import json
                        canvas_data = json.loads(canvas_data)

                    # Extract integration IDs from nodes
                    nodes = canvas_data.get('nodes', [])
                    required_integrations = set()
                    for node in nodes:
                        node_data = node.get('data', {})
                        config = node_data.get('config', {})
                        integration_id = config.get('integration_instance_id')
                        if integration_id:
                            required_integrations.add(integration_id)

                    # Check if required integrations are configured
                    if required_integrations:
                        configured = await conn.fetch(
                            """SELECT id, name, is_enabled FROM integration_instances
                               WHERE id = ANY($1::uuid[])""",
                            list(required_integrations)
                        )
                        configured_ids = {str(row['id']) for row in configured}
                        enabled_ids = {str(row['id']) for row in configured if row['is_enabled']}

                        # Check for missing integrations
                        missing = required_integrations - configured_ids
                        if missing:
                            blocking_reasons.append(f"Missing integrations: {len(missing)} required integrations not configured")

                        # Check for disabled integrations
                        disabled = configured_ids - enabled_ids
                        if disabled:
                            blocking_reasons.append(f"Disabled integrations: {len(disabled)} required integrations are disabled")

                can_run = len(blocking_reasons) == 0

                return AutonomyCheck(
                    can_run=can_run,
                    requires_approval=requires_approval,
                    blocking_reasons=blocking_reasons
                )

        except Exception as e:
            logger.error(f"Failed to check autonomy: {e}")
            return AutonomyCheck(
                can_run=False,
                blocking_reasons=[f"Error: {str(e)}"]
            )

    async def auto_execute_playbook(
        self,
        alert: Dict[str, Any],
        playbook_id: str = None
    ) -> Dict[str, Any]:
        """
        Riggs autonomously executes a playbook for an alert.
        """
        try:
            from services.playbook_engine import get_playbook_engine

            # Select playbook if not specified
            if not playbook_id:
                selection = await self.select_playbook_for_alert(alert)
                if not selection.selected_playbook:
                    return {
                        "error": "No suitable playbook found",
                        "reasons": selection.match_reasons
                    }
                playbook_id = selection.selected_playbook['id']

            # Check autonomy
            autonomy = await self.can_run_autonomously(playbook_id, alert)

            if not autonomy.can_run:
                return {
                    "error": "Cannot run autonomously",
                    "reasons": autonomy.blocking_reasons
                }

            if autonomy.requires_approval:
                # Create approval request
                return await self._request_playbook_approval(playbook_id, alert)

            # Execute playbook
            engine = get_playbook_engine()
            result = await engine.start_execution(
                playbook_id=playbook_id,
                trigger_context={
                    "alert": alert,
                    "alert_id": alert.get('id'),
                    "triggered_by": "riggs_auto"
                },
                triggered_by="riggs"
            )

            # Log decision
            await self._log_riggs_decision(
                decision_type="auto_execute",
                playbook_id=playbook_id,
                alert_id=alert.get('id'),
                result=result
            )

            return result

        except Exception as e:
            logger.error(f"Failed to auto-execute: {e}")
            return {"error": str(e)}

    # ========================================================================
    # Analysis
    # ========================================================================

    async def analyze_alert(self, alert: Dict[str, Any]) -> PlaybookAnalysis:
        """
        Analyze an alert and determine:
        1. What playbooks could handle it
        2. What's missing (integrations, data)
        3. Recommended actions
        4. Whether to run existing playbook or build new one
        """
        selection = await self.select_playbook_for_alert(alert)

        analysis = PlaybookAnalysis()
        analysis.matching_playbooks = [selection.selected_playbook] if selection.selected_playbook else []
        analysis.matching_playbooks.extend(selection.alternatives[:3])

        # Check for missing integrations based on alert type
        alert_type = alert.get('type', '').lower()

        if 'phishing' in alert_type or 'email' in alert_type:
            analysis.missing_integrations.extend([
                'virustotal', 'urlscan', 'email_gateway'
            ])
            analysis.recommended_actions.extend([
                {"action": "enrich_urls", "priority": "high"},
                {"action": "enrich_sender", "priority": "high"},
                {"action": "check_similar_emails", "priority": "medium"}
            ])

        elif 'malware' in alert_type or 'endpoint' in alert_type:
            analysis.missing_integrations.extend([
                'crowdstrike', 'carbon_black', 'virustotal'
            ])
            analysis.recommended_actions.extend([
                {"action": "isolate_host", "priority": "high"},
                {"action": "collect_forensics", "priority": "high"},
                {"action": "scan_hash", "priority": "medium"}
            ])

        elif 'network' in alert_type or 'intrusion' in alert_type:
            analysis.missing_integrations.extend([
                'firewall', 'ids', 'netflow'
            ])
            analysis.recommended_actions.extend([
                {"action": "block_ip", "priority": "high"},
                {"action": "analyze_traffic", "priority": "medium"}
            ])

        # Determine if should build new
        analysis.should_build_new = (
            selection.match_score < 30 or
            not selection.selected_playbook
        )

        analysis.analysis_summary = self._generate_analysis_summary(alert, selection, analysis)

        return analysis

    async def analyze_playbook(self, playbook_id: str) -> Dict[str, Any]:
        """
        Review existing playbook and suggest improvements.
        """
        try:
            from services.postgres_db import postgres_db

            async with postgres_db.tenant_acquire() as conn:
                playbook = await conn.fetchrow(
                    "SELECT * FROM playbooks WHERE id = $1",
                    uuid.UUID(playbook_id)
                )

                if not playbook:
                    return {"error": "Playbook not found"}

                canvas_data = playbook['canvas_data']
                if isinstance(canvas_data, str):
                    canvas_data = json.loads(canvas_data)

                nodes = canvas_data.get('nodes', [])
                edges = canvas_data.get('edges', [])

                suggestions = []

                # Check for error handling
                has_error_handling = any(
                    n.get('type') in ['condition', 'switch'] and
                    'error' in str(n.get('data', {}).get('config', {})).lower()
                    for n in nodes
                )
                if not has_error_handling:
                    suggestions.append(PlaybookRecommendation(
                        type="add_error_handling",
                        description="Add error handling for failed enrichments or actions",
                        reasoning="Playbooks should gracefully handle failures",
                        priority="high",
                        auto_apply=False
                    ))

                # Check for approval gates before actions
                action_nodes = [n for n in nodes if n.get('type') == 'action']
                for action_node in action_nodes:
                    action_config = action_node.get('data', {}).get('config', {})
                    if not action_config.get('requires_approval', True):
                        # Find upstream nodes
                        upstream = [e['source'] for e in edges if e['target'] == action_node['id']]
                        upstream_types = [
                            next((n['type'] for n in nodes if n['id'] == u), None)
                            for u in upstream
                        ]
                        if 'approval_gate' not in upstream_types:
                            suggestions.append(PlaybookRecommendation(
                                type="add_node",
                                description=f"Add approval gate before '{action_node.get('data', {}).get('label', 'action')}'",
                                reasoning="Response actions should have human approval",
                                priority="high",
                                auto_apply=False,
                                changes={"before_node": action_node['id'], "node_type": "approval_gate"}
                            ))

                # Check for missing enrichment
                trigger_node = next((n for n in nodes if n.get('type') == 'trigger'), None)
                enrich_nodes = [n for n in nodes if n.get('type') == 'enrich']
                if trigger_node and len(enrich_nodes) == 0:
                    suggestions.append(PlaybookRecommendation(
                        type="add_node",
                        description="Add enrichment step after trigger",
                        reasoning="Alerts should be enriched before decision making",
                        priority="medium",
                        auto_apply=True,
                        changes={"after_node": trigger_node['id'], "node_type": "enrich"}
                    ))

                # Check for end node
                has_end = any(n.get('type') == 'end' for n in nodes)
                if not has_end:
                    suggestions.append(PlaybookRecommendation(
                        type="add_node",
                        description="Add explicit end node",
                        reasoning="Playbooks should have clear completion points",
                        priority="low",
                        auto_apply=True,
                        changes={"node_type": "end"}
                    ))

                return {
                    "playbook_id": playbook_id,
                    "node_count": len(nodes),
                    "edge_count": len(edges),
                    "suggestions": [s.dict() for s in suggestions],
                    "suggestion_count": len(suggestions)
                }

        except Exception as e:
            logger.error(f"Failed to analyze playbook: {e}")
            return {"error": str(e)}

    # ========================================================================
    # Building
    # ========================================================================

    async def build_playbook(
        self,
        alert: Dict[str, Any],
        requirements: str = None
    ) -> PlaybookDraft:
        """
        Build a complete playbook from an alert.
        """
        alert_type = alert.get('type', alert.get('alert_type', 'generic')).lower()
        alert_severity = alert.get('severity', 'medium')

        # Generate playbook name
        name = f"Auto: {alert_type.replace('_', ' ').title()} Response"

        # Create nodes based on alert type
        nodes = []
        edges = []
        y_pos = 0

        # Trigger node
        trigger_id = f"trigger_{uuid.uuid4().hex[:6]}"
        nodes.append({
            "id": trigger_id,
            "type": "trigger",
            "position": {"x": 250, "y": y_pos},
            "data": {
                "label": "Alert Trigger",
                "config": {
                    "trigger_type": "alert",
                    "alert_types": [alert_type]
                }
            }
        })
        y_pos += 100

        # Riggs analyze node
        riggs_id = f"riggs_{uuid.uuid4().hex[:6]}"
        nodes.append({
            "id": riggs_id,
            "type": "riggs_analyze",
            "position": {"x": 250, "y": y_pos},
            "data": {
                "label": "Riggs Analysis",
                "config": {}
            }
        })
        edges.append({"id": f"e_{trigger_id}_{riggs_id}", "source": trigger_id, "target": riggs_id})
        y_pos += 100

        # Add enrichment based on alert type
        if 'phishing' in alert_type or 'email' in alert_type:
            enrich_id = f"enrich_{uuid.uuid4().hex[:6]}"
            nodes.append({
                "id": enrich_id,
                "type": "enrich",
                "position": {"x": 250, "y": y_pos},
                "data": {
                    "label": "Enrich URLs & Sender",
                    "config": {
                        "integrations": ["virustotal", "urlscan"],
                        "observable_type": "url"
                    }
                }
            })
            edges.append({"id": f"e_{riggs_id}_{enrich_id}", "source": riggs_id, "target": enrich_id})
            y_pos += 100
            prev_id = enrich_id
        elif 'malware' in alert_type:
            enrich_id = f"enrich_{uuid.uuid4().hex[:6]}"
            nodes.append({
                "id": enrich_id,
                "type": "enrich",
                "position": {"x": 250, "y": y_pos},
                "data": {
                    "label": "Enrich File Hash",
                    "config": {
                        "integrations": ["virustotal"],
                        "observable_type": "hash"
                    }
                }
            })
            edges.append({"id": f"e_{riggs_id}_{enrich_id}", "source": riggs_id, "target": enrich_id})
            y_pos += 100
            prev_id = enrich_id
        else:
            prev_id = riggs_id

        # Condition node based on verdict
        condition_id = f"cond_{uuid.uuid4().hex[:6]}"
        nodes.append({
            "id": condition_id,
            "type": "condition",
            "position": {"x": 250, "y": y_pos},
            "data": {
                "label": "Check Verdict",
                "config": {
                    "field": f"$.nodes.{riggs_id}.verdict",
                    "operator": "equals",
                    "value": "MALICIOUS"
                }
            }
        })
        edges.append({"id": f"e_{prev_id}_{condition_id}", "source": prev_id, "target": condition_id})
        y_pos += 120

        # True branch - take action
        approval_id = f"approval_{uuid.uuid4().hex[:6]}"
        nodes.append({
            "id": approval_id,
            "type": "approval_gate",
            "position": {"x": 100, "y": y_pos},
            "data": {
                "label": "Analyst Approval",
                "config": {
                    "message": "Riggs detected malicious activity. Approve response actions?",
                    "timeout_minutes": 30
                }
            }
        })
        edges.append({
            "id": f"e_{condition_id}_{approval_id}",
            "source": condition_id,
            "sourceHandle": "true",
            "target": approval_id
        })

        action_id = f"action_{uuid.uuid4().hex[:6]}"
        nodes.append({
            "id": action_id,
            "type": "action",
            "position": {"x": 100, "y": y_pos + 100},
            "data": {
                "label": "Response Action",
                "config": {
                    "action_type": "contain_host" if 'malware' in alert_type else "block_sender",
                    "requires_approval": False  # Already approved above
                }
            }
        })
        edges.append({"id": f"e_{approval_id}_{action_id}", "source": approval_id, "target": action_id})

        # False branch - notify
        notify_id = f"notify_{uuid.uuid4().hex[:6]}"
        nodes.append({
            "id": notify_id,
            "type": "notify",
            "position": {"x": 400, "y": y_pos},
            "data": {
                "label": "Notify Analyst",
                "config": {
                    "channel": "slack",
                    "message": "Alert reviewed - no malicious activity detected"
                }
            }
        })
        edges.append({
            "id": f"e_{condition_id}_{notify_id}",
            "source": condition_id,
            "sourceHandle": "false",
            "target": notify_id
        })

        # End nodes
        end_true_id = f"end_{uuid.uuid4().hex[:6]}"
        nodes.append({
            "id": end_true_id,
            "type": "end",
            "position": {"x": 100, "y": y_pos + 200},
            "data": {
                "label": "Contained",
                "config": {"disposition": "true_positive"}
            }
        })
        edges.append({"id": f"e_{action_id}_{end_true_id}", "source": action_id, "target": end_true_id})

        end_false_id = f"end_{uuid.uuid4().hex[:6]}"
        nodes.append({
            "id": end_false_id,
            "type": "end",
            "position": {"x": 400, "y": y_pos + 100},
            "data": {
                "label": "Benign",
                "config": {"disposition": "false_positive"}
            }
        })
        edges.append({"id": f"e_{notify_id}_{end_false_id}", "source": notify_id, "target": end_false_id})

        return PlaybookDraft(
            name=name,
            description=f"Automated response playbook for {alert_type} alerts",
            trigger_conditions={"alert_types": [alert_type]},
            canvas_data={"nodes": nodes, "edges": edges},
            tags=self._extract_alert_tags(alert),
            alert_types=[alert_type]
        )

    async def add_node(
        self,
        playbook_id: str,
        node_type: str,
        config: Dict[str, Any],
        connect_after: str = None,
        position: Dict[str, int] = None,
        reasoning: str = None
    ) -> Dict[str, Any]:
        """Add a new node to a playbook."""
        try:
            from services.postgres_db import postgres_db

            async with postgres_db.tenant_acquire() as conn:
                playbook = await conn.fetchrow(
                    "SELECT * FROM playbooks WHERE id = $1",
                    uuid.UUID(playbook_id)
                )

                if not playbook:
                    return {"error": "Playbook not found"}

                canvas_data = playbook['canvas_data']
                if isinstance(canvas_data, str):
                    canvas_data = json.loads(canvas_data)

                nodes = canvas_data.get('nodes', [])
                edges = canvas_data.get('edges', [])

                # Generate node ID
                node_id = f"{node_type}_{uuid.uuid4().hex[:6]}"

                # Calculate position
                if position:
                    pos = position
                elif connect_after:
                    after_node = next((n for n in nodes if n['id'] == connect_after), None)
                    if after_node:
                        pos = {
                            "x": after_node['position']['x'],
                            "y": after_node['position']['y'] + 100
                        }
                    else:
                        pos = {"x": 250, "y": len(nodes) * 100}
                else:
                    pos = {"x": 250, "y": len(nodes) * 100}

                # Create node
                new_node = {
                    "id": node_id,
                    "type": node_type,
                    "position": pos,
                    "data": {
                        "label": config.get('label', node_type.replace('_', ' ').title()),
                        "config": config
                    }
                }
                nodes.append(new_node)

                # Connect to previous node
                if connect_after:
                    edge_id = f"e_{connect_after}_{node_id}"
                    edges.append({
                        "id": edge_id,
                        "source": connect_after,
                        "target": node_id
                    })

                # Update playbook
                canvas_data['nodes'] = nodes
                canvas_data['edges'] = edges

                await conn.execute('''
                    UPDATE playbooks
                    SET canvas_data = $1,
                        updated_at = NOW(),
                        version = version + 1
                    WHERE id = $2
                ''', json.dumps(canvas_data), uuid.UUID(playbook_id))

                # Record suggestion
                if reasoning:
                    await self._record_suggestion(playbook_id, {
                        "type": "add_node",
                        "node_id": node_id,
                        "reasoning": reasoning
                    })

                return {
                    "success": True,
                    "node_id": node_id,
                    "node": new_node
                }

        except Exception as e:
            logger.error(f"Failed to add node: {e}")
            return {"error": str(e)}

    async def update_node(
        self,
        playbook_id: str,
        node_id: str,
        config: Dict[str, Any],
        reasoning: str = None
    ) -> Dict[str, Any]:
        """Update an existing node's configuration."""
        try:
            from services.postgres_db import postgres_db

            async with postgres_db.tenant_acquire() as conn:
                playbook = await conn.fetchrow(
                    "SELECT * FROM playbooks WHERE id = $1",
                    uuid.UUID(playbook_id)
                )

                if not playbook:
                    return {"error": "Playbook not found"}

                canvas_data = playbook['canvas_data']
                if isinstance(canvas_data, str):
                    canvas_data = json.loads(canvas_data)

                nodes = canvas_data.get('nodes', [])

                # Find and update node
                node_found = False
                for i, node in enumerate(nodes):
                    if node['id'] == node_id:
                        nodes[i]['data']['config'].update(config)
                        if 'label' in config:
                            nodes[i]['data']['label'] = config['label']
                        node_found = True
                        break

                if not node_found:
                    return {"error": "Node not found"}

                # Update playbook
                canvas_data['nodes'] = nodes

                await conn.execute('''
                    UPDATE playbooks
                    SET canvas_data = $1,
                        updated_at = NOW(),
                        version = version + 1
                    WHERE id = $2
                ''', json.dumps(canvas_data), uuid.UUID(playbook_id))

                return {"success": True, "node_id": node_id}

        except Exception as e:
            logger.error(f"Failed to update node: {e}")
            return {"error": str(e)}

    async def delete_node(
        self,
        playbook_id: str,
        node_id: str,
        reasoning: str = None
    ) -> Dict[str, Any]:
        """Delete a node and reconnect edges."""
        try:
            from services.postgres_db import postgres_db

            async with postgres_db.tenant_acquire() as conn:
                playbook = await conn.fetchrow(
                    "SELECT * FROM playbooks WHERE id = $1",
                    uuid.UUID(playbook_id)
                )

                if not playbook:
                    return {"error": "Playbook not found"}

                canvas_data = playbook['canvas_data']
                if isinstance(canvas_data, str):
                    canvas_data = json.loads(canvas_data)

                nodes = canvas_data.get('nodes', [])
                edges = canvas_data.get('edges', [])

                # Find incoming and outgoing edges
                incoming = [e for e in edges if e['target'] == node_id]
                outgoing = [e for e in edges if e['source'] == node_id]

                # Remove node
                nodes = [n for n in nodes if n['id'] != node_id]

                # Remove edges connected to this node
                edges = [e for e in edges if e['source'] != node_id and e['target'] != node_id]

                # Reconnect edges (connect incoming sources to outgoing targets)
                for inc in incoming:
                    for out in outgoing:
                        new_edge = {
                            "id": f"e_{inc['source']}_{out['target']}",
                            "source": inc['source'],
                            "target": out['target']
                        }
                        if inc.get('sourceHandle'):
                            new_edge['sourceHandle'] = inc['sourceHandle']
                        edges.append(new_edge)

                # Update playbook
                canvas_data['nodes'] = nodes
                canvas_data['edges'] = edges

                await conn.execute('''
                    UPDATE playbooks
                    SET canvas_data = $1,
                        updated_at = NOW(),
                        version = version + 1
                    WHERE id = $2
                ''', json.dumps(canvas_data), uuid.UUID(playbook_id))

                return {"success": True, "deleted_node_id": node_id}

        except Exception as e:
            logger.error(f"Failed to delete node: {e}")
            return {"error": str(e)}

    async def connect_nodes(
        self,
        playbook_id: str,
        source_id: str,
        source_port: str,
        target_id: str,
        target_port: str,
        data_path: str = None,
        reasoning: str = None
    ) -> Dict[str, Any]:
        """Create a connection between nodes."""
        try:
            from services.postgres_db import postgres_db

            async with postgres_db.tenant_acquire() as conn:
                playbook = await conn.fetchrow(
                    "SELECT * FROM playbooks WHERE id = $1",
                    uuid.UUID(playbook_id)
                )

                if not playbook:
                    return {"error": "Playbook not found"}

                canvas_data = playbook['canvas_data']
                if isinstance(canvas_data, str):
                    canvas_data = json.loads(canvas_data)

                edges = canvas_data.get('edges', [])

                # Create edge
                edge_id = f"e_{source_id}_{target_id}"
                new_edge = {
                    "id": edge_id,
                    "source": source_id,
                    "target": target_id
                }

                if source_port:
                    new_edge['sourceHandle'] = source_port
                if target_port:
                    new_edge['targetHandle'] = target_port
                if data_path:
                    new_edge['data'] = {'path': data_path}

                edges.append(new_edge)
                canvas_data['edges'] = edges

                await conn.execute('''
                    UPDATE playbooks
                    SET canvas_data = $1,
                        updated_at = NOW(),
                        version = version + 1
                    WHERE id = $2
                ''', json.dumps(canvas_data), uuid.UUID(playbook_id))

                return {"success": True, "edge_id": edge_id}

        except Exception as e:
            logger.error(f"Failed to connect nodes: {e}")
            return {"error": str(e)}

    # ========================================================================
    # Recommendations
    # ========================================================================

    async def recommend_improvements(
        self,
        playbook_id: str
    ) -> List[PlaybookRecommendation]:
        """Analyze playbook and recommend improvements."""
        analysis = await self.analyze_playbook(playbook_id)

        if "error" in analysis:
            return []

        return [
            PlaybookRecommendation(**s)
            for s in analysis.get('suggestions', [])
        ]

    async def recommend_integrations(
        self,
        playbook_id: str
    ) -> List[IntegrationRecommendation]:
        """Suggest integrations that would improve the playbook."""
        try:
            from services.postgres_db import postgres_db

            async with postgres_db.tenant_acquire() as conn:
                playbook = await conn.fetchrow(
                    "SELECT * FROM playbooks WHERE id = $1",
                    uuid.UUID(playbook_id)
                )

                if not playbook:
                    return []

                canvas_data = playbook['canvas_data']
                if isinstance(canvas_data, str):
                    canvas_data = json.loads(canvas_data)

                nodes = canvas_data.get('nodes', [])
                recommendations = []

                # Check existing integrations used
                used_integrations = set()
                for node in nodes:
                    config = node.get('data', {}).get('config', {})
                    if 'integration' in config:
                        used_integrations.add(config['integration'])
                    if 'integrations' in config:
                        used_integrations.update(config['integrations'])

                # Recommend based on alert types
                alert_types = playbook.get('alert_types', [])
                tags = playbook.get('tags', [])

                if any('phishing' in t.lower() for t in alert_types + tags):
                    if 'virustotal' not in used_integrations:
                        recommendations.append(IntegrationRecommendation(
                            integration_name="VirusTotal",
                            integration_type="threat_intel",
                            reason="Essential for URL and domain reputation checks in phishing investigations",
                            use_case="Enrich suspicious URLs and domains from phishing emails",
                            node_suggestions=[{"type": "enrich", "config": {"integration": "virustotal"}}]
                        ))
                    if 'urlscan' not in used_integrations:
                        recommendations.append(IntegrationRecommendation(
                            integration_name="URLScan.io",
                            integration_type="threat_intel",
                            reason="Provides screenshots and detailed analysis of suspicious URLs",
                            use_case="Visual inspection of phishing landing pages"
                        ))

                if any('malware' in t.lower() or 'endpoint' in t.lower() for t in alert_types + tags):
                    if 'crowdstrike' not in used_integrations:
                        recommendations.append(IntegrationRecommendation(
                            integration_name="CrowdStrike Falcon",
                            integration_type="edr",
                            reason="Leading EDR for endpoint containment and forensics",
                            use_case="Isolate infected hosts and collect process/file data"
                        ))

                # General recommendations
                if 'slack' not in used_integrations:
                    recommendations.append(IntegrationRecommendation(
                        integration_name="Slack",
                        integration_type="notification",
                        reason="Real-time notifications to SOC team",
                        use_case="Alert analysts when playbook requires attention"
                    ))

                return recommendations

        except Exception as e:
            logger.error(f"Failed to recommend integrations: {e}")
            return []

    async def apply_recommendation(
        self,
        playbook_id: str,
        recommendation: PlaybookRecommendation
    ) -> Dict[str, Any]:
        """Apply a recommendation to a playbook."""
        if recommendation.type == "add_node":
            changes = recommendation.changes
            return await self.add_node(
                playbook_id=playbook_id,
                node_type=changes.get('node_type'),
                config=changes.get('config', {}),
                connect_after=changes.get('after_node'),
                reasoning=recommendation.reasoning
            )
        elif recommendation.type == "update_node":
            changes = recommendation.changes
            return await self.update_node(
                playbook_id=playbook_id,
                node_id=changes.get('node_id'),
                config=changes.get('config', {}),
                reasoning=recommendation.reasoning
            )
        else:
            return {"error": f"Cannot auto-apply recommendation type: {recommendation.type}"}

    # ========================================================================
    # Custom Functions & Lists
    # ========================================================================

    async def create_function(
        self,
        name: str,
        description: str,
        code: str,
        input_schema: Dict[str, Any],
        output_schema: Dict[str, Any]
    ) -> Dict[str, Any]:
        """Create a custom Python function."""
        from services.playbook_sandbox import get_function_library

        library = get_function_library()
        return await library.create_function(
            name=name,
            description=description,
            code=code,
            input_schema=input_schema,
            output_schema=output_schema
        )

    async def create_list(
        self,
        name: str,
        list_type: str,
        items: List[Any],
        description: str = None
    ) -> Dict[str, Any]:
        """Create a custom list (allowlist, blocklist, etc.)."""
        try:
            from services.postgres_db import postgres_db

            from middleware.tenant_middleware import get_optional_tenant_id

            async with postgres_db.tenant_acquire() as conn:
                row = await conn.fetchrow('''
                    INSERT INTO playbook_lists (name, description, list_type, items, item_count, tenant_id)
                    VALUES ($1, $2, $3, $4, $5, $6)
                    RETURNING *
                ''',
                    name,
                    description,
                    list_type,
                    json.dumps(items),
                    len(items),
                    get_optional_tenant_id()
                )

                return {
                    "id": str(row['id']),
                    "name": row['name'],
                    "list_type": row['list_type'],
                    "item_count": row['item_count']
                }

        except Exception as e:
            logger.error(f"Failed to create list: {e}")
            return {"error": str(e)}

    async def update_list(
        self,
        list_id: str,
        add_items: List[Any] = None,
        remove_items: List[Any] = None
    ) -> Dict[str, Any]:
        """Add or remove items from a list."""
        try:
            from services.postgres_db import postgres_db

            async with postgres_db.tenant_acquire() as conn:
                list_row = await conn.fetchrow(
                    "SELECT * FROM playbook_lists WHERE id = $1",
                    uuid.UUID(list_id)
                )

                if not list_row:
                    return {"error": "List not found"}

                items = list_row['items']
                if isinstance(items, str):
                    items = json.loads(items)

                if add_items:
                    items.extend(add_items)
                    items = list(set(items))  # Dedupe

                if remove_items:
                    items = [i for i in items if i not in remove_items]

                await conn.execute('''
                    UPDATE playbook_lists
                    SET items = $1, item_count = $2, updated_at = NOW()
                    WHERE id = $3
                ''', json.dumps(items), len(items), uuid.UUID(list_id))

                return {
                    "success": True,
                    "item_count": len(items)
                }

        except Exception as e:
            logger.error(f"Failed to update list: {e}")
            return {"error": str(e)}

    # ========================================================================
    # Helpers
    # ========================================================================

    def _extract_alert_tags(self, alert: Dict[str, Any]) -> List[str]:
        """Extract relevant tags from an alert."""
        tags = []

        # From alert type
        alert_type = alert.get('type', alert.get('alert_type', ''))
        if alert_type:
            tags.extend(alert_type.lower().replace('-', '_').split('_'))

        # From title/description
        title = alert.get('title', '')
        if 'phishing' in title.lower():
            tags.append('phishing')
        if 'malware' in title.lower():
            tags.append('malware')
        if 'ransomware' in title.lower():
            tags.append('ransomware')
        if 'credential' in title.lower():
            tags.append('credential')

        # From severity
        severity = alert.get('severity', '')
        if severity:
            tags.append(severity.lower())

        # Dedupe
        return list(set(tags))

    def _generate_analysis_summary(
        self,
        alert: Dict[str, Any],
        selection: PlaybookSelection,
        analysis: PlaybookAnalysis
    ) -> str:
        """Generate human-readable analysis summary."""
        parts = []

        if selection.selected_playbook:
            parts.append(f"Found matching playbook: {selection.selected_playbook.get('name')}")
            parts.append(f"Match score: {selection.match_score:.0f}/100")
        else:
            parts.append("No existing playbook matches this alert type")

        if analysis.missing_integrations:
            parts.append(f"Recommended integrations: {', '.join(analysis.missing_integrations[:3])}")

        if analysis.should_build_new:
            parts.append("Recommendation: Build a new playbook for this alert type")

        return ". ".join(parts)

    async def _request_playbook_approval(
        self,
        playbook_id: str,
        alert: Dict[str, Any]
    ) -> Dict[str, Any]:
        """Create an approval request for playbook execution."""
        from services.postgres_db import postgres_db
        from datetime import datetime, timedelta

        try:
            async with postgres_db.tenant_acquire() as conn:
                # Get playbook name
                playbook = await conn.fetchrow(
                    "SELECT name FROM playbooks WHERE id = $1",
                    uuid.UUID(playbook_id)
                )
                playbook_name = playbook['name'] if playbook else 'Unknown Playbook'

                # Extract Riggs analysis from alert if available
                riggs_analysis = alert.get('riggs_analysis', {})
                riggs_verdict = riggs_analysis.get('verdict')
                riggs_confidence = riggs_analysis.get('confidence')

                # Generate approval request ID
                approval_id = f"APR-{datetime.utcnow().strftime('%Y%m%d%H%M%S')}-{str(uuid.uuid4())[:8].upper()}"

                # Set expiration to 24 hours from now
                expires_at = datetime.utcnow() + timedelta(hours=24)

                # Build reasoning
                alert_id = alert.get('alert_id', 'unknown')
                alert_title = alert.get('title', 'Security Alert')
                reasoning = f"Riggs recommends executing playbook '{playbook_name}' for alert '{alert_title}' (ID: {alert_id})"
                if riggs_verdict:
                    reasoning += f". Verdict: {riggs_verdict}"
                if riggs_confidence:
                    reasoning += f" (confidence: {riggs_confidence}%)"

                # Insert approval request
                await conn.execute('''
                    INSERT INTO playbook_execution_approvals (
                        id, investigation_id, playbook_id, playbook_name,
                        riggs_verdict, riggs_confidence, riggs_reasoning,
                        status, created_at, expires_at, tenant_id
                    ) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, NOW(), $9, $10)
                ''',
                    approval_id,
                    alert.get('investigation_id', alert.get('alert_id', 'unknown')),
                    uuid.UUID(playbook_id),
                    playbook_name,
                    riggs_verdict,
                    riggs_confidence,
                    reasoning,
                    'pending',
                    expires_at,
                    alert.get('tenant_id')
                )

                logger.info(f"[RIGGS] Created approval request {approval_id} for playbook {playbook_name}")

                return {
                    "status": "pending_approval",
                    "approval_id": approval_id,
                    "playbook_id": playbook_id,
                    "playbook_name": playbook_name,
                    "expires_at": expires_at.isoformat(),
                    "message": f"Playbook '{playbook_name}' requires approval before execution"
                }

        except Exception as e:
            logger.error(f"[RIGGS] Failed to create approval request: {e}")
            return {
                "status": "error",
                "playbook_id": playbook_id,
                "message": f"Failed to create approval request: {str(e)}"
            }

    async def _log_riggs_decision(
        self,
        decision_type: str,
        playbook_id: str,
        alert_id: str,
        result: Dict[str, Any]
    ):
        """Log Riggs decision for audit trail."""
        from services.postgres_db import postgres_db

        logger.info(
            f"[RIGGS_DECISION] type={decision_type} playbook={playbook_id} "
            f"alert={alert_id} success={result.get('success', False)}"
        )

        try:
            async with postgres_db.tenant_acquire() as conn:
                # Build decision summary
                success = result.get('success', False)
                status = 'success' if success else 'failed'
                decision_value = f"playbook_{status}:{playbook_id[:8]}" if playbook_id else status

                # Extract confidence and reasoning from result
                confidence = result.get('confidence')
                reasoning = result.get('reasoning') or result.get('message') or f"Playbook execution {status}"

                # Get investigation_id if available
                investigation_id = result.get('investigation_id')

                # Build evidence/recommendations from result
                evidence = {
                    'playbook_id': playbook_id,
                    'alert_id': alert_id,
                    'execution_result': {
                        'success': success,
                        'execution_id': result.get('execution_id'),
                        'error': result.get('error')
                    }
                }

                recommendations = result.get('recommendations', [])

                # Insert decision record
                from middleware.tenant_middleware import get_optional_tenant_id
                await conn.execute('''
                    INSERT INTO riggs_decisions (
                        investigation_id, decision_type, decision_value,
                        reasoning, confidence, evidence, recommendations,
                        created_by, tenant_id
                    ) VALUES (
                        $1, $2, $3, $4, $5, $6::jsonb, $7::jsonb, 'riggs_playbook_agent', $8
                    )
                ''',
                    uuid.UUID(investigation_id) if investigation_id else None,
                    decision_type,
                    decision_value,
                    reasoning,
                    confidence,
                    json.dumps(evidence),
                    json.dumps(recommendations),
                    get_optional_tenant_id()
                )

                logger.info(f"[RIGGS] Logged decision: {decision_type} for playbook {playbook_id}")

        except Exception as e:
            # Non-fatal - don't fail the main operation
            logger.warning(f"[RIGGS] Failed to log decision to database: {e}")

    async def _record_suggestion(
        self,
        playbook_id: str,
        suggestion: Dict[str, Any]
    ):
        """Record a Riggs suggestion in the playbook."""
        try:
            from services.postgres_db import postgres_db

            async with postgres_db.tenant_acquire() as conn:
                await conn.execute('''
                    UPDATE playbooks
                    SET riggs_suggestions = COALESCE(riggs_suggestions, '[]'::jsonb) || $1::jsonb,
                        last_riggs_review = NOW()
                    WHERE id = $2
                ''',
                    json.dumps([suggestion]),
                    uuid.UUID(playbook_id)
                )
        except Exception as e:
            logger.error(f"Failed to record suggestion: {e}")

    def _row_to_dict(self, row) -> Dict[str, Any]:
        """Convert database row to dictionary."""
        if not row:
            return None

        result = dict(row)

        for field in ['id', 'created_by']:
            if result.get(field):
                result[field] = str(result[field])

        for field in ['created_at', 'updated_at', 'last_riggs_review']:
            if result.get(field):
                result[field] = result[field].isoformat()

        for field in ['canvas_data', 'trigger_conditions', 'riggs_suggestions']:
            if result.get(field) and isinstance(result[field], str):
                try:
                    result[field] = json.loads(result[field])
                except:
                    pass

        return result


# ============================================================================
# Singleton
# ============================================================================

_agent: Optional[RiggsPlaybookAgent] = None


def get_riggs_playbook_agent() -> RiggsPlaybookAgent:
    """Get singleton Riggs playbook agent instance."""
    global _agent
    if _agent is None:
        _agent = RiggsPlaybookAgent()
    return _agent
